// AUTO-GENERATED by scripts/build-rental-terms-data.py — do not hand-edit.
// Source: C:/Users/lenovo/Documents/LuxeClub Car Rentals — Rental Terms Draft.docx
// Generated: 2026-06-25

export interface RentalTermsSubsection {
  heading: string
  paragraphs: string[]
}

export interface RentalTermsSection {
  heading: string
  intro: string[]
  subs: RentalTermsSubsection[]
}

export const rentalTermsTitle = "LuxeClub Car Rentals UAE — Rental Terms & Conditions (Draft)"
export const rentalTermsSubtitle = ""
export const rentalTermsLastUpdated = "2026-06-25"

export const rentalTermsSections: RentalTermsSection[] = [
  {
    heading: "United Arab Emirates - Passenger vehicle",
    intro: [
    ],
    subs: [
    ],
  },
  {
    heading: "General Rental Information",
    intro: [
      "As stated in the Terms & Conditions, reservations apply solely to the chosen vehicle category. If not stated otherwise, a specific make and model is not guaranteed. The renter confirms that he has read and accepts the Terms & Conditions when completing the booking.",
    ],
    subs: [
      {
        heading: "Important documents",
        paragraphs: [
          "The renter and all approved drivers must be in possession of a full, valid driving licence for at least one year. Furthermore, the following conditions apply depending on the issuing country of the driving licence.",
          "United Arab Emirates residents require a United Arab Emirates driver's license.",
          "Drivers from the GCC countries are required to present original passport and driving license at the counter. GCC identification cards, photocopies or digital licenses will not be accepted.",
          "Customers on resident / employment visa or if the resident visa is under process are required to have a UAE driving licence which must be at least one year old. If the UAE driving licence is less than one year old then a supporting driving licence providing that the driver has been driving more than 1 year is required.",
          "Drivers from the countries not listed below are only permitted to drive with an international driving licence supported by the original home country licence.",
          "If the drivers licence was issued outside the origin country, then a valid current residence visa or working permit is required.",
          "Valid national driving licenses from the following countries are accepted: North America: Canada (national only), USA (with the exception of the State of Texas), Texas (USA) (national only) East Asia & Pacific: Australia (national only), Azerbaijan (national only), China (national only), Hong Kong, Israel (national only), Japan, New Zealand (national only), Singapore (national only), South Korea (national only), Uzbekistan (national only) Europe: Albania (national only), Austria, Belarus (national only), Belgium, Britain, Bulgaria (national only), Croatia (national only), Cyprus (national only), Denmark, Estonia (national only), Finland, France, Germany, Greece (national only), Hungary (national only), Iceland (national only), Ireland (national only), Italy, Latvia (national only), Lithuania (national only), Luxembourg (national only), Malta (national only), Montenegro (national only), Netherlands, Norway, Poland, Portugal(national only), Romania, Serbia(national only), Slovakia(national only), Slovenia (national only), Spain, Sweden, Switzerland, Turkey, Ukraine (national only), United Kingdom Middle East: Bahrain, Kuwait, Oman, Saudi Arabia, Qatar Africa: South Africa",
          "LuxeClub Car Rentals supports Chinese customers with the necessary translations via LuxeClub Car Rentals. This or any other kind of valid translation of the driving license can only be accepted if accompanied by the original driving license.",
          "Customers must present a valid passport in Roman alphabet at the time of rental as proof of identification.",
          "Kindly note that we require the following documents upon handling over the vehicle: - Passport copy supported by the original passport, - Driving License Copy - supported by the original driving license that should be above one year old (or more depending on the car group, please refer to Age Restrictions), - Valid Credit Card only - Customers on pre-arranged entry visas will be required to present proof of entry visa.",
          "Photocopies, digital licenses, Learner's Permits, and driver's licenses with driving restrictions will not be accepted.",
          "Kindly note that we require the following documents for Long Term Rentals: - proof of residence (tenancy contract or title deed copy) - valid visa copy supported by the original visa stamp in the passport - 1 undated security cheque as security towards rental for long term rentals. Once rental is completed and all outstanding amounts have been cleared, the cheque will be returned.",
        ],
      },
      {
        heading: "Age Restrictions",
        paragraphs: [
          "In United Arab Emirates, the following rules apply for the minimum age and possession of a driver's license. The minimum age to rent any vehicle is 21.",
          "A Young Driver Surcharge applies for drivers under 25 years.",
          "Any driver under the age of 25 years is not permitted to accept any Loss damage waiver with minimum excess options.",
        ],
      },
    ],
  },
  {
    heading: "Tariff information",
    intro: [
    ],
    subs: [
      {
        heading: "General",
        paragraphs: [
          "Cash Payment is not accepted.",
          "The following credit cards are accepted: all credit cards from internationally recognised credit card companies - such as American Express, Diners Club, Eurocard/Mastercard, Visa. We do not accept any prepaid cards. Debit cards (Visa Electron) are only accepted in exceptional cases. The renter must be the owner of the indicated credit card.",
          "Debit Cards are accepted on the following conditions: - The renter does not have a valid Credit card for the rental. - The renter agrees to and signs the Terms and Conditions of the Debit Card Addendum Form. - Card processing fees apply to all Debit Card rental agreements except for GCC nationalities. An additional security deposit of 1,000.00 AED will be payable. - The Rental and Security Deposit will be charged/purchased to the Debit Card and a refund for the balance of the rental will only be processed after 25 working days. All debit cards must be in the main renter's name",
          "The security deposit amount varies and depends on the vehicle type. The exact deposit for each car is shown on the vehicle's page on luxeclubrentals.com. The deposit is held as a refundable pre-authorisation on the chosen means of payment at collection and released once the vehicle is returned and inspected, usually within five working days. A no-deposit option is available to drivers who have held a full driving licence for more than five years — please let our team know at booking.",
        ],
      },
      {
        heading: "Special rental information when booking Prepaid rates",
        paragraphs: [
        ],
      },
      {
        heading: "Prepaid tariff - Pay now",
        paragraphs: [
          "When booking at a prepaid rate, the payment will be charged along with the total rental price (incl. booked extras and charges) prior to the rental. The driver and mode of payment shall be finalised at the time of reservation and cannot be changed. The confirmed credit card should be valid and available for presentation and verification on collection of the vehicle. All extra costs that occur during the car rental will be charged to this credit card. A refund shall not be issued for non-collection, vehicle being collected late or returned early.",
          "Changing booking",
          "A prepaid booking can be changed up to 48 hours before the start of the rental (depending on availability) in return for a booking modification fee of 105,00 AE. Any payment already made towards the rental will not be refunded; nor shall any differential amount be refunded if this modification leads to a lesser rental cost. Any changes made to a prepaid reservation may impact the rental rate. A change from a prepaid rate to a non-prepaid rate is not possible.",
          "Cancellation",
          "A booking can be cancelled before the rental begins. In the event of cancellation, the payment in advance already made towards the rental shall be paid back subject to a cancellation charge, which will be withheld and shall be in the amount of the rental charge (including any extras and charges) for a maximum of 3 rental days. Cancellations can be made online or in writing and must be addressed to: LuxeClub Car Rentals, Binary Tower, 32 Marasi Drive, Business Bay, Dubai, United Arab Emirates. Email: bookings@luxeclubrentals.com · WhatsApp: +971(0) 50 610 1375.",
          "Cancellations or changes made within 24 hours of booking can be completed free of charge, provided the scheduled pick-up time is more than 48 hours away.",
          "No-show In the event that the booked vehicle is not collected or not collected at the agreed time the rental charge already paid shall be withheld in full.",
        ],
      },
    ],
  },
  {
    heading: "Protection conditions",
    intro: [
      "A police record is obligatory for all protections. In case that the driver does not ensure police presence or a police record, the full amount for the damage and/or theft will be charged to the driver irrespective of the kind of the purchased protection.",
    ],
    subs: [
      {
        heading: "Third Party Insurance (TI)",
        paragraphs: [
          "Protection coverage for the vehicle includes Third Party Liability with a maximum cover of 1 Million AED for material damages. Maximum cover for personal injuries is unlimited per injured person.",
          "Excluded from the protection is the use of the vehicle for the transport of dangerous goods. All protection as part of the rental contract will become void, in particular, if an unauthorized driver has used the vehicle or if the driver of the vehicle does not possess the required driver's license at the time of the event giving rise to claim or if the vehicle is driven off-road or on a race track.",
        ],
      },
      {
        heading: "Loss Damage Waiver (LDW)",
        paragraphs: [
          "Loss damage waiver (incl. theft protection) removes the drivers responsibility to a part of the vehicle in case of damage or theft.",
          "If loss damage waiver (incl. theft protection) is accepted, the customer is only responsible for the following amounts: 3,000.00 AED (MCAR, EFAR, CCAR, CDAR, CFAR, CFBR, SDAR, MDAR, EDAR, ECAR) 5,000.00 AED (CLAR, CBAR) 7,000.00 AED (CCCC, IDAR, ILAR, SCAR, SFAR, SFBR, SGAR, SLAR, SSAR, SVAR, FDAR, FFAR, JFAR, LCAR, PDAR, PFAR, RFAR, SXAR, ICAR, FCAR, PCAR) 8,000.00 AED (FVAR, GFAR, LDAR, LFAR, LFAX, PFBR, PXBR, XJAR, XLAR, LDAV, LFAN) 10,000.00 AED (XDAR, XFAR, XTAX) 12,000.00 AED (XFAX, XTAR, XXAR) 30,000.00 AED (XSAR)",
          "If loss damage waiver (incl. theft protection) is not accepted the customer will be held liable for the full value of the car.",
        ],
      },
      {
        heading: "Loss damage waiver (including Theft Protection) with reduced excess (BE)",
        paragraphs: [
          "If LDW is already included in the rates, the renter can choose Loss damage waiver (including Theft Protection) with reduced excess to further reduce the Non-Waiverable Responsibility.",
          "If Loss damage waiver (including Theft Protection) with reduced excess is accepted, customer is only responsible for the following liability amounts: 1,500.00 AED (MCAR, EFAR, CCAR, CDAR, CFAR, CFBR, SDAR, MDAR, EDAR, ECAR) 2,500.00 AED (CLAR, CBAR) 3,500.00 AED (CCCC, IDAR, ILAR, SCAR, SFAR, SFBR, SGAR, SLAR, SSAR, SVAR, FDAR, FFAR, JFAR, LCAR, PDAR, PFAR, RFAR, SXAR, ICAR, FCAR, PCAR) 4,000.00 AED (FVAR, GFAR, LDAR, LFAR, LFAX, PFBR, PXBR, XJAR, XLAR, LDAV, LFAN) 7,000.00 AED (XDAR, XFAR, XTAX) 10,000.00 AED (XFAX, XXAR, XTAR) 15,000.00 AED (XSAR)",
        ],
      },
      {
        heading: "Loss damage waiver (including Theft Protection) with minimum excess (BF)",
        paragraphs: [
          "If LDW is already included in the rates, the renter can choose Loss damage waiver (including Theft Protection) with minimum excess to eliminate the Non-Waiverable Responsibility, provided the driver is 25 years of age or older.",
          "Loss damage waiver (including Theft Protection) with minimum excess is not offered on the XSAR and XTAX car groups.",
          "If Loss damage waiver (including Theft Protection) with minimum excess is accepted, customer is only responsible for the following amounts: 0.00 AED",
        ],
      },
      {
        heading: "Interior Protection",
        paragraphs: [
          "By taking out insurance protection for the interior, liability in the event of damage or soil to the vehicle interior can be reduced to a predetermined deductible or eliminated.",
        ],
      },
      {
        heading: "Personal Accident Protection (PAP)",
        paragraphs: [
          "By taking out personal accident protection coverage can also be extended to cover the consequences of an accident.",
          "By taking out personal accident protection the limit of liability is: AED 200,000.00 per person.",
          "Additionally, this protection includes liability waiver for any Covid 19 related vehicle sanitation charges and free collection due to Covid 19 disease.",
        ],
      },
      {
        heading: "Tyre and Windscreen Coverage",
        paragraphs: [
          "The tyre and glass coverage provides protection for damages on tyres, windscreen, side windows and the rear window with a deductible of EUR 0.00.",
          "If no tyre and glass cover has been arranged, the leaser shall be liable for up to the full amount of the damage.",
        ],
      },
    ],
  },
  {
    heading: "Cross Border Rentals & Territorial Restrictions",
    intro: [
      "Cross-border rentals are not permitted. LuxeClub Car Rentals vehicles must remain within the United Arab Emirates for the entire rental period. Driving the vehicle outside the UAE — including but not limited to Oman, Saudi Arabia, and Qatar — is strictly prohibited.",
      "Any cross-border use voids all insurance and damage protections, exposes the renter to full vehicle replacement liability, and may trigger a fixed penalty in addition to recovery and repatriation costs.",
    ],
    subs: [
    ],
  },
  {
    heading: "Extras",
    intro: [
      "Accessories are bookable without obligation and subject to availability.",
    ],
    subs: [
      {
        heading: "One-Way Rentals",
        paragraphs: [
          "One-way rentals within LuxeClub Car Rentals locations in the United Arab Emirates are allowed under conditions depending on tariff.",
          "International One-Way Rentals are not allowed.",
          "In the case of unannounced and unauthorised one-way rentals, we reserve the right to charge an additional fee.",
        ],
      },
      {
        heading: "Navigation system",
        paragraphs: [
          "Navigation systems are available subject to a fee.",
        ],
      },
      {
        heading: "Additional Driver",
        paragraphs: [
          "A fee is charged for additional drivers, whereby only persons named in the rental agreement with a valid driver's license are permitted to drive the vehicle.",
        ],
      },
      {
        heading: "Baby and child seats",
        paragraphs: [
          "Baby seats, child seats and booster seats are available subject to a fee.",
        ],
      },
      {
        heading: "Vehicle refueling",
        paragraphs: [
          "All vehicles are supplied with a full tank of fuel and should be refilled prior to return to LuxeClub Car Rentals, otherwise the current prices per litre of petrol or diesel will be charged in addition to a refuelling fee.",
          "If desired, the vehicle will be refuled according to currently available conditions after returning it to the station.",
          "Alternatively, you may purchase a full tank of fuel at the beginning of the rental at a price that is competitive with local fuel stations and can then return the tank empty. No refunds will be given for unused fuel.",
          "You may purchase a whole tank of fuel at the time of the reservation and return the tank empty. No refunds will be given for unused fuel.",
          "Fuelling service: Subject to availability at the respective branch, you can book our \"Fuelling service\" at the specified price and thereby return the vehicle without a full fuel tank. In this case, you will only be charged for the subsequently fuelled litres of fuel at comparable fuel station prices, in addition to the above-mentioned fee.",
        ],
      },
      {
        heading: "Delivery and collection",
        paragraphs: [
          "Deliveries and collections are available at the local rental station subject to a fee.",
          "This service is available on request for an additional commitment fee outside opening times at selected locations.",
          "The renter is obliged to report the vehicle back to LuxeClub Car Rentals at the end of the rental period.",
        ],
      },
      {
        heading: "Roadside protection",
        paragraphs: [
          "The roadside protection is an extended breakdown protection during the rental and protects you at home and abroad against high service and repair costs for the following incidents caused by you: key locked in vehicle, breaking caused by lack of fuel, assistance with starting necessitated by flat battery, loss of key and vehicle stuck.",
        ],
      },
      {
        heading: "Personal Travel Assistant - LuxeClub Car Rentals Connect",
        paragraphs: [
          "LuxeClub Car Rentals Connects are available subject to a fee.",
          "The LuxeClub Car Rentals Connect WIFI includes GPS, a tourist guide and a WIFI access point (up to 3 devices) with mobile internet.",
        ],
      },
    ],
  },
  {
    heading: "Other Fees and Taxes",
    intro: [
    ],
    subs: [
      {
        heading: "Premium Location Fee",
        paragraphs: [
          "A premium location fee occurs for rentals at airport and train stations.",
        ],
      },
      {
        heading: "Out of Opening Hours",
        paragraphs: [
          "Out of opening hours service is available at selected stations. In this case, an additional charge applies for the provision of the service.",
        ],
      },
      {
        heading: "Vehicle License Fee",
        paragraphs: [
          "A Vehicle License Fee occurs.",
        ],
      },
      {
        heading: "Road Tax",
        paragraphs: [
          "In Dubai a toll fee (Salik) may apply. The car is equipped with a Salik tag, which is attached to the windscreen. Each time a vehicle passes a Salik toll station a fee applies. Toll Fees / Salik will be automatically charged on the customers credit card on a daily basis.",
          "Moving or removing the Salik tag is not allowed and a penalty charge will be applied for this.",
          "Express Toll Unlimited You can purchase our optional Express Toll Unlimited which offers unlimited use of automated toll lanes in Dubai, Sharjah and Abu Dhabi.",
          "If the Express Toll Unlimited is not purchased, an administration fee will be charged in addition to each the road toll (Salik).",
        ],
      },
      {
        heading: "Parking",
        paragraphs: [
          "Parking charges will be automatically charged on the customers credit card on a daily basis.",
          "An administration fee is charged for each parking ticket",
        ],
      },
      {
        heading: "Loss Of Key",
        paragraphs: [
          "In the event of a lost or damaged key or key-ring/key-fob a fee applies.",
        ],
      },
      {
        heading: "Smell-Removal-Fee",
        paragraphs: [
          "All LuxeClub Car Rentals cars are non-smoking cars. If a car needs additional cleaning/smell-removal caused by smoking, a fee will be added to the invoice.",
        ],
      },
      {
        heading: "Sanitation Fee",
        paragraphs: [
          "Special Sanitation Fee and collection fee will be charged in the event of Covid 19 case if Personal Accident Protection was declined.",
          "(Sanitation Fee = OT)",
        ],
      },
      {
        heading: "Vehicle Cleaning",
        paragraphs: [
          "In case the car requires a special cleaning procedure after returning, a charge will apply. It is also possible to book the vehicle cleaning beforehand.",
        ],
      },
      {
        heading: "Flexi Return Guarantee",
        paragraphs: [
          "Plans can change. As a flexible mobility partner, we are happy to adapt to your plans. Thanks to our Flexi Return guarantee, you have the freedom to return the vehicle at any time, regardless of the rental agreement. If your plans change during your hire period, let us know on WhatsApp (+971(0) 50 610 1375) or by email (bookings@luxeclubrentals.com) and our team will amend your rental contract. This service is free of charge.",
        ],
      },
      {
        heading: "Flexi Return Guarantee in the tariff Pay later",
        paragraphs: [
          "If you return your vehicle earlier than agreed in the rental contract, we will charge the rental price according to the rental contract. You will receive a partial discount for the unused rental days.",
        ],
      },
      {
        heading: "Flexi Return Guarantee in the tariff Pay now",
        paragraphs: [
          "When booking at a prepaid rate, a refund shall not be issued for returned early. For further information please refer to the section Prepaid Tariff - Pay now.",
        ],
      },
      {
        heading: "Flexi Late Return in both tariffs (Pay later & Pay now)",
        paragraphs: [
          "If you return the vehicle later, without notifying us, we will bill you AED 42.00 service fee for the Flexi Return Service. This fee applies in addition to any extra days which might incur due to the rental extension.",
        ],
      },
      {
        heading: "Flexi Return Location in both tariffs (Pay later & Pay now)",
        paragraphs: [
          "If you return the vehicle to a station other than that agreed in the rental contract, the Flexi Return location will incur a service fee of AED 67.20 if we have not been informed of the changes to the rental contract in advance. With our Flexi Return guarantee, you will always have maximum flexibility and cost-efficiency when driving.",
        ],
      },
    ],
  },
]
