"""Extract the LuxeClub Car Rentals Draft docx into lib/rental-terms.ts.

Reads:  C:/Users/lenovo/Documents/LuxeClub Car Rentals — Rental Terms Draft.docx
Writes: lib/rental-terms.ts (auto-generated; do not hand-edit)
"""
import sys
import json
from pathlib import Path
from datetime import date
from docx import Document

sys.stdout.reconfigure(encoding="utf-8")

PROJECT = Path("C:/Users/lenovo/projects/luxeclub-rentals")
SRC = Path("C:/Users/lenovo/Documents/LuxeClub Car Rentals — Rental Terms Draft.docx")
OUT = PROJECT / "lib" / "rental-terms.ts"

doc = Document(SRC)


def heading_level(style_name: str) -> int | None:
    if style_name == "Title":
        return 0
    if style_name and style_name.startswith("Heading"):
        try:
            return int(style_name.split(" ")[-1])
        except ValueError:
            return None
    return None


# Group paragraphs into sections keyed by their preceding H2 / H3.
title = ""
subtitle = ""
# top-level structure: list of H2 sections, each with a list of H3 subsections.
# H3 subsection: {heading, paragraphs: string[]}
# H2 section:    {heading, intro_paragraphs: string[], subsections: H3[]}
sections: list[dict] = []
current_h2: dict | None = None
current_h3: dict | None = None

for i, p in enumerate(doc.paragraphs):
    text = " ".join(p.text.split()).strip()
    if not text:
        continue
    lvl = heading_level(p.style.name if p.style else "")

    if lvl == 0:
        title = text
        continue
    if i == 1 and not lvl:
        # subtitle paragraph immediately after the title
        subtitle = text
        continue

    if lvl == 1 or lvl == 3 and current_h2 is None:
        # Treat any stray H1 (e.g. "United Arab Emirates - Passenger vehicle") as a top-level section.
        current_h2 = {"heading": text, "intro": [], "subs": []}
        sections.append(current_h2)
        current_h3 = None
    elif lvl == 2:
        current_h2 = {"heading": text, "intro": [], "subs": []}
        sections.append(current_h2)
        current_h3 = None
    elif lvl == 3:
        current_h3 = {"heading": text, "paragraphs": []}
        if current_h2 is None:
            current_h2 = {"heading": "General", "intro": [], "subs": []}
            sections.append(current_h2)
        current_h2["subs"].append(current_h3)
    elif lvl == 4:
        # Treat H4 as an in-section subheading by prefixing the paragraph with **bold**.
        para = f"**{text}**"
        if current_h3:
            current_h3["paragraphs"].append(para)
        elif current_h2:
            current_h2["intro"].append(para)
    else:
        # Plain paragraph.
        if current_h3:
            current_h3["paragraphs"].append(text)
        elif current_h2:
            current_h2["intro"].append(text)
        # else: stray paragraph before the first heading — drop.

# Serialise to TypeScript. Use JSON encoding for strings to handle quotes/unicode safely.
def js(s: str) -> str:
    """JSON-encode a string so it's safe as a TS string literal."""
    return json.dumps(s, ensure_ascii=False)


lines: list[str] = []
lines.append("// AUTO-GENERATED by scripts/build-rental-terms-data.py — do not hand-edit.")
lines.append("// Source: C:/Users/lenovo/Documents/LuxeClub Car Rentals — Rental Terms Draft.docx")
lines.append(f"// Generated: {date.today().isoformat()}")
lines.append("")
lines.append("export interface RentalTermsSubsection {")
lines.append("  heading: string")
lines.append("  paragraphs: string[]")
lines.append("}")
lines.append("")
lines.append("export interface RentalTermsSection {")
lines.append("  heading: string")
lines.append("  intro: string[]")
lines.append("  subs: RentalTermsSubsection[]")
lines.append("}")
lines.append("")
lines.append(f"export const rentalTermsTitle = {js(title)}")
lines.append(f"export const rentalTermsSubtitle = {js(subtitle)}")
lines.append(f"export const rentalTermsLastUpdated = {js(date.today().isoformat())}")
lines.append("")
lines.append("export const rentalTermsSections: RentalTermsSection[] = [")
for sec in sections:
    lines.append("  {")
    lines.append(f"    heading: {js(sec['heading'])},")
    lines.append("    intro: [")
    for para in sec["intro"]:
        lines.append(f"      {js(para)},")
    lines.append("    ],")
    lines.append("    subs: [")
    for sub in sec["subs"]:
        lines.append("      {")
        lines.append(f"        heading: {js(sub['heading'])},")
        lines.append("        paragraphs: [")
        for para in sub["paragraphs"]:
            lines.append(f"          {js(para)},")
        lines.append("        ],")
        lines.append("      },")
    lines.append("    ],")
    lines.append("  },")
lines.append("]")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {OUT}")
print(f"  Title: {title}")
print(f"  Subtitle: {subtitle[:80]}...")
print(f"  Top-level sections: {len(sections)}")
print(f"  Total subsections: {sum(len(s['subs']) for s in sections)}")
print(f"  Total paragraphs: {sum(len(s['intro']) + sum(len(sub['paragraphs']) for sub in s['subs']) for s in sections)}")
